### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dhstewart** [ManageIQ/kubeclient#588]
Hello! Thanks for all the work you do on this gem, it's appreciated!

Will you be publishing a new release to [RubyGems](https://rubygems.org/gems/kubeclient/)  that includes the dependency updates in https://github.com/ManageIQ/kubeclient/commit/a83fd436e1cddb295fba1a1bc02b7f1e0dbb43ec soon?

Anything we can do to help get that released?

Thanks again!

**Comment by cben** [comment]
Hi, thanks for the nag :-|
The whole process of backporting to v4.y branch so that I can get things
released is annoying — it's eating much of the (too little) time I have for
kubeclient.  So I figured before I do that, I'll make some progress towards
a v5 release from master (specifically started assembling changelog, I'm
like 3% done...).

Anyway, let's parallelize.  Can you send a PR backporting same dependency
change onto `v4.y` branch?

**Comment by dhstewart** [comment]
Thanks for the reply @cben ! Been working on this here and there as I have time 😄 

We can move the conversation over to [this PR for the backport](https://github.com/ManageIQ/kubeclient/pull/589 ) I opened if you want 👍 

Thanks again 🎉 !
